### ISSUE TITLE
Crash On Startup with Rainmeter 3.5.2

### ISSUE THREAD

**Issue by dragonshardz** [i2002/RainmeterMediaPlayer#1]
Not sure why, but trying to call this plugin causes Rainmeter 3.5.2 to crash. All I have to provide is the Event Viewer data:

`Faulting application name: Rainmeter.exe, version: 4.5.13.3632, time stamp: 0x623b740e
Faulting module name: ucrtbase.dll, version: 10.0.19041.789, time stamp: 0x2bd748bf
Exception code: 0xc0000409
Fault offset: 0x000000000007286e
Faulting process id: 0x9dc8
Faulting application start time: 0x01d8577d9d4882d7
Faulting application path: C:\Program Files\Rainmeter\Rainmeter.exe
Faulting module path: C:\WINDOWS\System32\ucrtbase.dll
Report Id: c2f76a1c-f40b-460c-8d2d-4e5d019c7cb3
Faulting package full name: 
Faulting package-relative application ID: `

**Comment by i2002** [comment]
Hi, sorry for late reply

First of all, I think you mean Rainmeter version 4.5.2 as it says in the error log you wrote (I don't think the plugin works at all with version 3.5.2). 

I have Rainmeter version 4.5.13.3632 (64-bit) (the same as in the error log) in Windows 10 21H1 and I don't have this problem.

It may be because you have an older version of the C++ runtime (currently installed I have 14.31; however any version higher than 14.20 should work) (you can see the version in Settings -> Apps and Features; note that it should have x64 at the end if you have installed the 64bit version of Rainmeter and this plugin, or x86 for the 32 bit version)
![image](https://user-images.githubusercontent.com/36770606/166714184-e6068e5f-82b6-4bbf-af7d-78adb7e6ed95.png)

If that doesn't help, maybe it's because of older Windows version. However any version of Windows 10 higher than 1809 should work.

Also, have you used the sample skin or a custom skin that uses the dll? If so, you could post the skin so that I can try to reproduce the error. Maybe there's a bug at plugin options parsing.

**Comment by dragonshardz** [comment]
I do have Rainmeter 4.5.2, yes. Not sure where that 3 came from!

I also have the latest version of Windows 10 and C++ redist. I was poking around JaxCore's stuff and _apparently_ there's a current bug in Windows with the Performance Counters database (which, I guess, is where the information this plugin pulls is stored). 

Direct link to the comment: https://www.deviantart.com/comments/1/881628513/4984231328

I did personally run into a problem with those commands where the one run in system32 returned an error, but running winmgmt.exe /RESYNCPERF in the syswow64 directory fixed it.

As of now my issue is fixed, but you may want to add those steps to a FAQ or something for anyone who runs into the same problem!

**Comment by i2002** [comment]
Hm, I see..
The thing is this plugin doesn't use the Performance Counters you mention.
Also, if it was an issue in Windows 10 I should have also been affected.

From the information we have I'm not sure exactly if the problem it's caused by this plugin specifically (and no way to test this).
If more people seem to be affected by this I'll write about this in the repository description.

I'm glad that you managed to solve your problem.

**Comment by KK-Designs** [comment]
> I do have Rainmeter 4.5.2, yes. Not sure where that 3 came from!
> 
> I also have the latest version of Windows 10 and C++ redist. I was poking around JaxCore's stuff and _apparently_ there's a current bug in Windows with the Performance Counters database (which, I guess, is where the information this plugin pulls is stored).
> 
> Direct link to the comment: https://www.deviantart.com/comments/1/881628513/4984231328
> 
> I did personally run into a problem with those commands where the one run in system32 returned an error, but running winmgmt.exe /RESYNCPERF in the syswow64 directory fixed it.
> 
> As of now my issue is fixed, but you may want to add those steps to a FAQ or something for anyone who runs into the same problem!

What does the `winmgmt.exe /RESYNCPERF` command do?

**Comment by dragonshardz** [comment]
Based on context, it resynchronizes the performance counters.
