### ISSUE TITLE
[Bug Report] It caused Rainmeter to crash in Windows 8

### ISSUE THREAD

**Issue by SteveHsuDrawing** [i2002/RainmeterMediaPlayer#2]
<img width="826" alt="21" src="https://github.com/i2002/RainmeterMediaPlayer/assets/122773837/f14504e9-77ad-4af1-8030-de16c0a666b8">

I know it's impossible to display information in Windows 8, but when called in Windows 8, it causes Rainmeter to crash.

In Windows 7 it also does not display information, but it does not crash.

Rainmeter version: 4.5.18.3727 (64-bit)

**Comment by i2002** [comment]
Hi,

To be honest, the stranger thing is it doesn't crash in Windows 7. Because this plugin uses Windows 10 APIs to get the media information, the plugin dll should be dynamically linked to system libraries that are present in Windows 10, but which were not there in Windows 8 or 7. Therefore it should crash on both systems.

What I believe it may be happening is that in Windows 7 it crashes right away and Rainmeter knows just to disable the plugin and moves on, whereas in Windows 8 which might have more similarities with Windows 10 maybe the plugin doesn't crash at load, but during operation and that makes Rainmeter to crash.

Unfortunately I don't have a Win 7 or Win 8 machine to test, and I believe it is not a use case that should necessarily be supported (the minimum requirements specified are Win 10 after a specific build). Technically it should be possible for the plugin to detect the windows version and decide to load or not the libraries, however if you run it on Windows 7 or 8 in this case it won't crash but it won't work either.

If you believe there might be a use case where someone would want to have the plugin not crash in win 7 or 8 but also not working as intended, please let me know.

Have a great day
